// authUser
export const CHANGE_AUTH_USER = 'CHANGE_AUTH_USER'
export const SET_AUTH_USER_USERNAME = 'SET_AUTH_USER_USERNAME'
// comments
export const ADD_COMMENTS = 'ADD_COMMENTS'
export const SET_COMMENTS_OVER = 'SET_COMMENTS_OVER'
export const CREATE_COMMENT = 'CREATE_COMMENT'